### PR TITLE
feat: No unused vars

### PR DESCRIPTION
**Pull request by JonaszJestem**
use case:

Code with bug:
```
  async findByRole(role: Role): Promise<User | null> {
    return (
      Object.values(this.db).find((user) => user.role === Role.Retailer) ?? null
    );
  }
```

With this rule eslint reports error on function argument:
`ESLint: 'role' is defined but never used.(@typescript-eslint/no-unused-vars)`

### CODE REVIEW

**Comment by soanvig** [comment]
I'm actually against this rule personally.
For me it should not be an error. Warn at most.

If I have some draft code, and run eslint before recompilation, my code cannot be built and I have to clean up it and lose time (or worse if I have automatic correction - it gets automatically removed)

@tdzienniak
@Drajvon WDYT?

**Comment by maciekgrzybek** [comment]
I think that `warn` would be a good fit here 👌

**Comment by soanvig** [comment]
By the way, we also have config for react, they should be similar

**Comment by tdzienniak** [comment]
I don't like these unused vars in prod code, but I agree that it is nice to have during development. So "warn" is ok, because warns would (and should) fail the production build in most cases.

**Review by tdzienniak — APPROVED** [review]

**Review by soanvig — APPROVED** [review]

**Pull request merged**
